on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

name: Fetch and store

jobs:
  fetch:
    name: Fetch and store
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Scrape
      run: |
        yarn
        node fetch-and-store.js
        node generate-csv.js
    - name: Push data
      run: |
          git config user.name jxeeno
          git config user.email ken+github@jxeeno.com
          git add . || exit 0
          git commit -m "auto(): update data" || exit 0
          git push || exit 0
